name: daincrementer_example
description: Example code for the daincrementer library.
version: 1.0.0+1
homepage: https://github.com/mauriciotogneri/daincrementer

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter