name: daincrementer
description: A Dart package to automatically increments the version code of your pubspec.
version: 1.2.0
homepage: https://github.com/mauriciotogneri/daincrementer

environment:
  sdk: '>=2.12.0 <3.0.0'